apiVersion: v1
kind: Service
metadata:
  name: team1-springboot-service-jenkins-kyn
  namespace: group1-team1
spec:
  selector:
    app: team1-springboot-service-jenkins-kyn
  ports:
    - protocol: TCP
      port: 80  # 클러스터 내부에서 접근할 포트
      targetPort: 8080  # Spring Boot 컨테이너 내부 포트
      nodePort: 30120	# 외부에서 접근할 수 있는 포트 (30000~32767)
  type: NodePort  # 내부 통신용 (외부 접근하려면 LoadBalancer 또는 NodePort)
